name: Build PromoTronik hourly

on:
  schedule:
    - cron: "15 * * * *"   # toutes les heures à HH:15 (UTC)
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python generate_site.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: refresh site"
